workdir = ""

folders = [
  "src/entrypoints/http/public/routers/{{module.snake.many}}",
  "src/entrypoints/http/public/deps/{{module.snake.many}}",
  "src/application/usecases/{{module.snake.many}}",
  "src/application/usecases/{{module.snake.many}}/get",
  "src/infrastructure/databases/postgres/adapters/repositories",
  "src/infrastructure/databases/postgres/crud",
  "src/infrastructure/databases/postgres/tables",
  "src/domain/models",
  "src/domain/collections/exceptions"
]

# =========================
# EntryPoints / HTTP Public
# =========================

[[files]]
mode = "a"
path = "src/entrypoints/http/public/routers/registry.py"
content = """
from . import {{module.snake.many}}

router.include_router({{module.snake.many}}.router, tags=["{{module.pascal.many}}"])
"""

[[files]]
path = "src/entrypoints/http/public/routers/{{module.snake.many}}/__init__.py"
content = """
from .registry import router


__all__ = [
    "router",
]
"""

[[files]]
path = "src/entrypoints/http/public/routers/{{module.snake.many}}/registry.py"
content = """
from src.framework.routing import APIRouter

from . import create
from . import current
from . import delete


router = APIRouter()

router.include_router(current.router)
router.include_router(create.router)
router.include_router(delete.router)
"""

[[files]]
path = "src/entrypoints/http/public/routers/{{module.snake.many}}/create.py"
content = """
from fastapi import Body
from fastapi import Depends
from fastapi import status

from src.application.usecases.{{module.snake.many}}.create import Usecase
from src.domain.collections import {{module.pascal.single}}AlreadyExists
from src.entrypoints.http.public.deps.{{module.snake.many}}.create import dependency
from src.entrypoints.http.public.schemas import Create{{module.pascal.single}}
from src.framework.openapi.utils import errors
from src.framework.routing import APIRouter
from src.infrastructure.security.jwt.models import Tokens


router = APIRouter()


@router.post(
    "/{{module.kebab.many}}:create",
    description="{{module.pascal.single}} create",
    response_model=Tokens,
    status_code=status.HTTP_201_CREATED,
    responses=errors({{module.pascal.single}}AlreadyExists),
)
async def command(
    usecase: Usecase = Depends(dependency),
    body: Create{{module.pascal.single}} = Body(...),
) -> Tokens:
    return await usecase(**body.deserialize())
"""

[[files]]
path = "src/entrypoints/http/public/routers/{{module.snake.many}}/current.py"
content = """
from fastapi import Depends
from fastapi import status

from src.domain.collections import {{module.pascal.single}}Blocked
from src.domain.collections import {{module.pascal.single}}NotFound
from src.domain.models import {{module.pascal.single}}
from src.entrypoints.http.common.collections import AUTHORIZATION_ERRORS
from src.entrypoints.http.common.deps import {{module.snake.single}}
from src.entrypoints.http.public.schemas import Current{{module.pascal.single}}
from src.framework.openapi.utils import errors
from src.framework.routing import APIRouter


router = APIRouter()


@router.get(
    "/{{module.kebab.many}}:current",
    description="Get current {{module.snake.single}}",
    response_model=Current{{module.pascal.single}},
    status_code=status.HTTP_200_OK,
    responses={
        status.HTTP_401_UNAUTHORIZED: {},
        **errors(
            *AUTHORIZATION_ERRORS,
            {{module.pascal.single}}NotFound,
            {{module.pascal.single}}Blocked,
        ),
    },
)
async def query(_{{module.snake.single}}: {{module.pascal.single}} = Depends({{module.snake.single}})) -> Current{{module.pascal.single}}:
    return Current{{module.pascal.single}}.serialize(_{{module.snake.single}})
"""

[[files]]
path = "src/entrypoints/http/public/routers/{{module.snake.many}}/delete.py"
content = """
from fastapi import Depends
from fastapi import Response
from fastapi import status

from src.application.usecases.{{module.snake.many}}.delete import Usecase
from src.common.formats.utils import field
from src.domain.collections import {{module.pascal.single}}Blocked
from src.domain.collections import {{module.pascal.single}}NotFound
from src.domain.models import {{module.pascal.single}}
from src.entrypoints.http.common.collections import AUTHORIZATION_ERRORS
from src.entrypoints.http.common.deps import {{module.snake.single}}
from src.entrypoints.http.public.deps.{{module.snake.many}}.delete import dependency
from src.framework.openapi.utils import errors
from src.framework.routing import APIRouter


router = APIRouter()


@router.delete(
    "/{{module.kebab.many}}:delete",
    description="{{module.pascal.single}} delete",
    response_class=Response,
    status_code=status.HTTP_204_NO_CONTENT,
    responses={
        status.HTTP_401_UNAUTHORIZED: {},
        **errors(
            *AUTHORIZATION_ERRORS,
            {{module.pascal.single}}NotFound,
            {{module.pascal.single}}Blocked,
        ),
    },
)
async def command(
    usecase: Usecase = Depends(dependency),
    _{{module.snake.single}}: {{module.pascal.single}} = Depends({{module.snake.single}}),
) -> None:
    return await usecase({{module.snake.single}}_id=field.required(_{{module.snake.single}}.id))
"""

[[files]]
path = "src/entrypoints/http/public/deps/{{module.snake.many}}/create.py"
content = """
from fastapi import Depends

from src.application.usecases.{{module.snake.many}}.create import Container
from src.application.usecases.{{module.snake.many}}.create import Repositories
from src.application.usecases.{{module.snake.many}}.create import Security
from src.application.usecases.{{module.snake.many}}.create import Usecase
from src.entrypoints.http.common.deps import write
from src.infrastructure.databases.orm.sqlalchemy.session import Session


def dependency(session: Session = Depends(write)) -> Usecase:
    return Usecase(container=Container(repositories=Repositories(session), security=Security()))
"""

[[files]]
path = "src/entrypoints/http/public/deps/{{module.snake.many}}/delete.py"
content = """
from fastapi import Depends

from src.application.usecases.{{module.snake.many}}.delete import Container
from src.application.usecases.{{module.snake.many}}.delete import Repositories
from src.application.usecases.{{module.snake.many}}.delete import Usecase
from src.entrypoints.http.common.deps import write
from src.infrastructure.databases.orm.sqlalchemy.session import Session


def dependency(session: Session = Depends(write)) -> Usecase:
    return Usecase(container=Container(repositories=Repositories(session)))
"""

[[files]]
path = "src/entrypoints/http/public/deps/{{module.snake.many}}/get.py"
content = """
from fastapi import Depends

from src.application.usecases.{{module.snake.many}}.get.jwt import Container
from src.application.usecases.{{module.snake.many}}.get.jwt import Repositories
from src.application.usecases.{{module.snake.many}}.get.jwt import Security
from src.application.usecases.{{module.snake.many}}.get.jwt import Usecase
from src.entrypoints.http.common.deps import read
from src.infrastructure.databases.orm.sqlalchemy.session import Session


def dependency(session: Session = Depends(read)) -> Usecase:
    return Usecase(container=Container(repositories=Repositories(session), security=Security()))
"""

[[files]]
path = "src/entrypoints/http/public/schemas/{{module.snake.many}}.py"
content = """
import typing

from src.common.formats.utils import field
from src.domain.models import {{module.pascal.single}}
from src.entrypoints.http.common.schemas import Command
from src.entrypoints.http.common.schemas import Request
from src.entrypoints.http.common.schemas import Response

from .base import Public


class Create{{module.pascal.single}}(Public, Request, Command):
    external_id: str


class Current{{module.pascal.single}}(Public, Response):
    id: int

    @classmethod
    def serialize(cls, model: {{module.pascal.single}}) -> typing.Self:
        return cls(id=field.required(model.id))
"""

[[files]]
mode = "a"
path = "src/entrypoints/http/public/schemas/__init__.py"
content = """
from .{{module.snake.many}} import Create{{module.pascal.single}}
from .{{module.snake.many}} import Current{{module.pascal.single}}
"""

# =========================
# Application / Usecases
# =========================

[[files]]
path = "src/application/usecases/{{module.snake.many}}/create.py"
content = """
from src.domain.collections import {{module.pascal.single}}AlreadyExists
from src.domain.models import {{module.pascal.single}}
from src.infrastructure.databases.orm.sqlalchemy.queries import Filter
from src.infrastructure.databases.orm.sqlalchemy.session import Session
from src.infrastructure.databases.postgres import adapters
from src.infrastructure.security.encryption import encryption
from src.infrastructure.security.jwt import jwt
from src.infrastructure.security.jwt.models import Tokens


class Repositories:
    def __init__(self, session: Session) -> None:
        self.{{module.snake.single}} = adapters.repositories.{{module.pascal.single}}(session)


class Security:
    def __init__(self) -> None:
        self.encryption = encryption
        self.jwt = jwt


class Container:
    def __init__(self, repositories: Repositories, security: Security) -> None:
        self.repositories = repositories
        self.security = security


class Usecase:
    def __init__(self, container: Container) -> None:
        self.container = container

    async def __call__(self, external_id: str) -> Tokens:
        if await self.container.repositories.{{module.snake.single}}.exists(
            Filter.eq(
                key="external_id",
                value=self.container.security.encryption.encrypt(external_id.lower()),
            )
        ):
            raise {{module.pascal.single}}AlreadyExists

        model = await self.container.repositories.{{module.snake.single}}.create(
            model={{module.pascal.single}}.init(
                **{{module.pascal.single}}.encrypt(
                    encrypter=self.container.security.encryption.encrypt,
                    external_id=external_id,
                )
            )
        )

        return self.container.security.jwt.encode(subject=str(model.id))
"""

[[files]]
path = "src/application/usecases/{{module.snake.many}}/delete.py"
content = """
from src.infrastructure.databases.orm.sqlalchemy.queries import Filter
from src.infrastructure.databases.orm.sqlalchemy.session import Session
from src.infrastructure.databases.postgres import adapters


class Repositories:
    def __init__(self, session: Session) -> None:
        self.{{module.snake.single}} = adapters.repositories.{{module.pascal.single}}(session)


class Container:
    def __init__(self, repositories: Repositories) -> None:
        self.repositories = repositories


class Usecase:
    def __init__(self, container: Container) -> None:
        self.container = container

    async def __call__(self, {{module.snake.single}}_id: int) -> None:
        await self.container.repositories.{{module.snake.single}}.delete(
            Filter.eq(key="id", value={{module.snake.single}}_id)
        )
"""

[[files]]
path = "src/application/usecases/{{module.snake.many}}/get/external.py"
content = """
from src.common.formats.utils import string
from src.domain.collections import {{module.pascal.single}}Blocked
from src.domain.models import {{module.pascal.single}}
from src.infrastructure.databases.orm.sqlalchemy.queries import Filter
from src.infrastructure.databases.orm.sqlalchemy.session import Session
from src.infrastructure.databases.postgres import adapters
from src.infrastructure.security.encryption import encryption


class Repositories:
    def __init__(self, session: Session) -> None:
        self.{{module.snake.single}} = adapters.repositories.{{module.pascal.single}}(session)


class Security:
    def __init__(self) -> None:
        self.encryption = encryption


class Container:
    def __init__(self, repositories: Repositories, security: Security) -> None:
        self.repositories = repositories
        self.security = security


class Usecase:
    def __init__(self, container: Container) -> None:
        self.container = container

    async def __call__(self, external_id: str) -> {{module.pascal.single}}:
        encrypted = self.container.security.encryption.encrypt(string.lower(external_id))

        model = await self.container.repositories.{{module.snake.single}}.one(
            Filter.eq(key="external_id", value=encrypted)
        )

        if model.blocked:
            raise {{module.pascal.single}}Blocked

        return model
"""

[[files]]
path = "src/application/usecases/{{module.snake.many}}/get/jwt.py"
content = """
from src.domain.collections import {{module.pascal.single}}Blocked
from src.domain.models import {{module.pascal.single}}
from src.infrastructure.databases.orm.sqlalchemy.queries import Filter
from src.infrastructure.databases.orm.sqlalchemy.session import Session
from src.infrastructure.databases.postgres import adapters
from src.infrastructure.security.jwt import jwt
from src.infrastructure.security.jwt.collections import TokenPurpose


class Repositories:
    def __init__(self, session: Session) -> None:
        self.{{module.snake.single}} = adapters.repositories.{{module.pascal.single}}(session)


class Security:
    def __init__(self) -> None:
        self.jwt = jwt


class Container:
    def __init__(self, repositories: Repositories, security: Security) -> None:
        self.repositories = repositories
        self.security = security


class Usecase:
    def __init__(self, container: Container) -> None:
        self.container = container

    async def __call__(self, token: str) -> {{module.pascal.single}}:
        {{module.snake.single}}_id = int((self.container.security.jwt.decode(token, TokenPurpose.access)).sub)

        model = await self.container.repositories.{{module.snake.single}}.one(
            Filter.eq(key="id", value={{module.snake.single}}_id)
        )

        if model.blocked:
            raise {{module.pascal.single}}Blocked

        return model
"""

[[files]]
path = "src/application/usecases/{{module.snake.many}}/__init__.py"
content = """
from . import create
from . import delete
from . import get


__all__ = [
    "create",
    "delete",
    "get",
]
"""

[[files]]
path = "src/application/usecases/{{module.snake.many}}/get/__init__.py"
content = """
from . import external
from . import jwt


__all__ = [
    "external",
    "jwt",
]
"""

# =========================
# Domain
# =========================

[[files]]
path = "src/domain/models/{{module.snake.single}}.py"
content = """
import datetime
import typing

from src.common.formats.utils import date

from .base import Base


class {{module.pascal.single}}(Base):
    __encrypted__ = ["external_id"]

    id: int | None
    external_id: str
    created: datetime.datetime
    updated: datetime.datetime
    blocked: datetime.datetime | None
    authorization: datetime.datetime | None

    @classmethod
    def init(cls, external_id: str) -> typing.Self:
        created = updated = date.now()

        return cls(
            id=None,
            external_id=external_id,
            created=created,
            updated=updated,
            blocked=None,
            authorization=None,
        )
"""

[[files]]
mode = "a"
path = "src/domain/models/__init__.py"
content = """
from .{{module.snake.single}} import {{module.pascal.single}}
"""

[[files]]
path = "src/domain/collections/exceptions/{{module.snake.single}}.py"
content = """
from src.common.http.collections import HTTPError


class {{module.pascal.single}}NotFound(HTTPError): ...
class {{module.pascal.single}}Blocked(HTTPError): ...
class {{module.pascal.single}}AlreadyExists(HTTPError): ...
"""

[[files]]
mode = "a"
path = "src/domain/collections/exceptions/__init__.py"
content = """
from .{{module.snake.single}} import {{module.pascal.single}}AlreadyExists
from .{{module.snake.single}} import {{module.pascal.single}}Blocked
from .{{module.snake.single}} import {{module.pascal.single}}NotFound
"""

# =========================
# Infrastructure / Postgres
# =========================

[[files]]
path = "src/infrastructure/databases/postgres/adapters/repositories/{{module.snake.single}}.py"
content = """
from src.domain import models
from src.domain.collections import exceptions
from src.infrastructure.databases.postgres import crud
from src.infrastructure.databases.postgres import tables

from .base import Base


class {{module.pascal.single}}(Base[crud.{{module.pascal.single}}, tables.{{module.pascal.single}}, models.{{module.pascal.single}}, exceptions.{{module.pascal.single}}NotFound]):
    crud = crud.{{module.pascal.single}}
    table = tables.{{module.pascal.single}}
    model = models.{{module.pascal.single}}
    error = exceptions.{{module.pascal.single}}NotFound
"""

[[files]]
mode = "a"
path = "src/infrastructure/databases/postgres/adapters/repositories/__init__.py"
content = """
from .{{module.snake.single}} import {{module.pascal.single}}
"""

[[files]]
path = "src/infrastructure/databases/postgres/crud/{{module.snake.single}}.py"
content = """
from src.infrastructure.databases.orm.sqlalchemy.crud import Base
from src.infrastructure.databases.postgres import tables


class {{module.pascal.single}}(Base[tables.{{module.pascal.single}}]):
    table = tables.{{module.pascal.single}}
"""

[[files]]
mode = "a"
path = "src/infrastructure/databases/postgres/crud/__init__.py"
content = """
from .{{module.snake.single}} import {{module.pascal.single}}
"""

[[files]]
path = "src/infrastructure/databases/postgres/tables/{{module.snake.single}}.py"
content = """
from sqlalchemy import BigInteger
from sqlalchemy import Column
from sqlalchemy import DateTime
from sqlalchemy import String

from src.infrastructure.databases.orm.sqlalchemy.tables import Base
from src.infrastructure.databases.postgres.collections import LENGTH_SMALL_STR


class {{module.pascal.single}}(Base):
    __tablename__ = "{{module.snake.single}}"

    id = Column(BigInteger, primary_key=True)

    external_id = Column(String(length=LENGTH_SMALL_STR), nullable=False, unique=True)

    created = Column(DateTime(timezone=True), nullable=False)
    updated = Column(DateTime(timezone=True), nullable=False)
    blocked = Column(DateTime(timezone=True), nullable=True)
    authorization = Column(DateTime(timezone=True), nullable=True)
"""

[[files]]
mode = "a"
path = "src/infrastructure/databases/postgres/tables/__init__.py"
content = """
from .{{module.snake.single}} import {{module.pascal.single}}
"""
